/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-sidebar': 'var(--color-bg-sidebar)',
        'bg-app': 'var(--color-bg-app)',
        'bg-surface': 'var(--color-bg-surface)',
        'bg-surface-hover': 'var(--color-bg-surface-hover)',
        'bg-surface-selected': 'var(--color-bg-surface-selected)',
        'bg-tag': 'var(--color-bg-tag)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'text-disabled': 'var(--color-text-disabled)',
        'text-on-dark': 'var(--color-text-on-dark)',
        'text-on-brand': 'var(--color-text-on-brand)',
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-active': 'var(--color-primary-active)',
        'primary-subtle': 'var(--color-primary-subtle)',
        'focus-ring': 'var(--color-focus-ring)',
        profit: 'var(--color-profit)',
        'profit-bg': 'var(--color-profit-bg)',
        loss: 'var(--color-loss)',
        'loss-bg': 'var(--color-loss-bg)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        danger: 'var(--color-danger)',
        'border-subtle': 'var(--color-border-subtle)',
        'border-default': 'var(--color-border-default)',
        'border-strong': 'var(--color-border-strong)',
      },
      fontFamily: {
        serif: ['Anthropic Serif', 'Noto Serif SC', 'Georgia', 'serif'],
        sans: ['Anthropic Sans', 'Noto Sans SC', '-apple-system', 'sans-serif'],
        mono: ['Anthropic Mono', 'JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '24px',
      },
      boxShadow: {
        ring: '0px 0px 0px 1px #d1cfc5',
        'ring-brand': '0px 0px 0px 1px #c96442',
        card: '0 2px 8px rgba(20,20,19,0.06)',
        panel: '-4px 0 24px rgba(20,20,19,0.08)',
        modal: '0 8px 32px rgba(20,20,19,0.12)',
      },
    },
  },
  plugins: [],
}
