"""initial_schema

Revision ID: e3c275bdf5a2
Revises: 
Create Date: 2026-05-30 14:50:01.235313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.types import Money


# revision identifiers, used by Alembic.
revision: str = 'e3c275bdf5a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('daily_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('close', Money(), nullable=False),
    sa.Column('pre_close', Money(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'trade_date', name='uq_daily_price')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_table('index_daily_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index_code', sa.String(length=12), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('close', Money(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_code', 'trade_date', name='uq_index_daily')
    )
    op.create_table('rule_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('raw_import_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('parsed', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('stock_name', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('price', Money(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', Money(), nullable=False),
    sa.Column('fee', Money(), nullable=False),
    sa.Column('market', sa.String(length=4), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('raw_row_id', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_row_id'], ['raw_import_rows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'stock_code', 'side', 'price', 'quantity', 'amount', name='uq_trade_identity')
    )
    op.create_index('ix_trades_stock_code', 'trades', ['stock_code'], unique=False)
    op.create_index('ix_trades_trade_date', 'trades', ['trade_date'], unique=False)
    op.create_table('review_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('stock_code', sa.String(length=10), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('rule_version_id', sa.Integer(), nullable=True),
    sa.Column('input_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_intents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('stock_code', sa.String(length=10), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_intents')
    op.drop_table('review_reports')
    op.drop_index('ix_trades_trade_date', table_name='trades')
    op.drop_index('ix_trades_stock_code', table_name='trades')
    op.drop_table('trades')
    op.drop_table('raw_import_rows')
    op.drop_table('tags')
    op.drop_table('rule_versions')
    op.drop_table('index_daily_cache')
    op.drop_table('import_batches')
    op.drop_table('daily_prices')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
